{% set name = "django-admin-rangefilter" %}
{% set version = "0.12.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-admin-rangefilter-{{ version }}.tar.gz
  sha256: 963df82cc948f938bd437df27db4b2649688034ae3045d748bbaf7686f712a70

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=4.2

test:
  imports:
    - rangefilter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/silentsokolov/django-admin-rangefilter
  summary: django-admin-rangefilter app, add the filter by a custom date range on the admin UI.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
