{% set name = "django-admin-rangefilter" %}
{% set version = "0.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 12750c32c01d6cc891ba7d05267ce9921527042084da0ac9548a3ae8109f90d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2

test:
  imports:
    - rangefilter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/silentsokolov/django-admin-rangefilter
  summary: django-admin-rangefilter app, add the filter by a custom date range on the admin UI.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
