# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: django-admin-rangefilter
  version: "0.13.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_admin_rangefilter-${{ version }}.tar.gz
  sha256: 8151b840753ea2c4de9963b1904cbbe7e786b7bc04de5dbd64567c86d287bbe8

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - django >=4.2

tests:
  - python:
      imports:
        - rangefilter
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: django-admin-rangefilter app, add the filter by a custom date range on the admin UI.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/silentsokolov/django-admin-rangefilter

extra:
  recipe-maintainers:
    - rxm7706
